### ISSUE TITLE
Unnecessary get() call in aggregate example

### ISSUE THREAD

**Issue by RobertBlackhart** [NetApp/ONTAP-REST-API#1]
https://github.com/NetApp/ONTAP-REST-API/blob/8bbc8e4a0dcf19bbe41d998c271802ac08795381/ONTAP_REST_API_Python_Client_Library/list_aggregates_pcl.py#L29-L31

The get call on this line is unnecessary. The line should be deleted. The name field already comes back in the `get_collection()` call. If you wanted to print some other field that didn't come back by default, then you would just add it to the call: `get_collection(fields="state")`

The same is true in the Volume list example

**Comment by jacobjohnanda** [comment]
Thanks Rob. I have fixed the issue.
